modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL="https://modrinth.com/mod/bovines-and-buttercups"
[[mods]]
modId = "bovinesandbuttercups"
version = "${file.jarVersion}"
displayName = "Bovines and Buttercups"
updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/GreenhouseTeam/bovines-and-buttercups"
logoFile = "bovinesandbuttercups.png"
credits = "Thanks for this example mod goes to Java"
authors = "${mod_author}"
description = '''
A mod that aims to provide a fresh take on the Moobloom mob from 2020's Mob Vote.
'''
[[dependencies.bovinesandbuttercups]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bovinesandbuttercups]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"
